export const ADD_ARTICLES = 'ADD_ARTICLES';
export const DELETE_ARTICLES = 'DELETE_ARTICLES';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';